### ISSUE TITLE
Unable to launch tft-testsuite

### ISSUE THREAD

**Issue by IvanMikhailov** [BorderCloud/TFT#3]
That's my the first and the only attempt to use the thing:

TFT$ ./tft-testsuite -a -t fuseki -q http://localhost:8820/sparql -u http://localhost:8820/sparql
 PHP Fatal error:  Call to undefined function curl_init() in lib/sparql/Curl.php on line 41

The commits in use are as follows:

$ git clone  --recursive https://github.com/BorderCloud/TFT.git
Cloning into 'TFT'...
remote: Counting objects: 348, done.
remote: Total 348 (delta 0), reused 0 (delta 0), pack-reused 348
Receiving objects: 100% (348/348), 94.72 KiB | 137.00 KiB/s, done.
Resolving deltas: 100% (216/216), done.
Checking connectivity... done.
Submodule 'lib/sparql' (https://github.com/BorderCloud/SPARQL.git) registered for path 'lib/sparql'
Submodule 'tests/TFT-tests' (https://github.com/BorderCloud/TFT-tests.git) registered for path 'tests/TFT-tests'
Cloning into 'lib/sparql'...
remote: Counting objects: 203, done.
remote: Total 203 (delta 0), reused 0 (delta 0), pack-reused 203
Receiving objects: 100% (203/203), 55.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (121/121), done.
Checking connectivity... done.
Submodule path 'lib/sparql': checked out '9c7fd5caef0c77ede9ce265ec32fa6fcda24688c'
Cloning into 'tests/TFT-tests'...
remote: Counting objects: 1178, done.
remote: Total 1178 (delta 0), reused 0 (delta 0), pack-reused 1177
Receiving objects: 100% (1178/1178), 184.82 KiB | 108.00 KiB/s, done.
Resolving deltas: 100% (433/433), done.
Checking connectivity... done.
Submodule path 'tests/TFT-tests': checked out 'b2ef414a16af11420b91f8623f1d99bd7fc702ea'

(tried 2016-Dec-18)

I've never dealt with php so I don't know what should I try next. Any instructions are welcome.

**Comment by BorderCloud** [comment]
Hello @IvanMikhailov 

You need to install Curl and php-curl. 
Example with ubuntu & fedora :
```
# apt-get install curl php5-curl
apt-get install curl php70w-common
or
# yum install curl php5-curl
yum / dnf install curl php70w-common
```

Bye
