### ISSUE TITLE
Relax `10 Substract date` test

### ISSUE THREAD

**Issue by masda70** [BorderCloud/TFT#5]
Stardog is returning a `xsd:dayTimeDuration` instead of `xsd:duration` as the type for the value `PT55M`. Now, I couldn't find the reference to the standard describing the expected the datatype for a datetime difference, but since [`xsd:dayTimeDuration` is a subclass of `xsd:duration`](https://www.w3.org/TR/xmlschema11-2/#dayTimeDuration), I think that the result should be considered valid.

Also note that the expected result provides more digits, e.g., `PT55M0.000S`, but I don't know is this would be a problem as well.

http://sparqlscore.com/ajax_testResultNode.php?graph=https%3A%2F%2Ftravis-ci.org%2FBorderCloud%2Ftft-stardog%2Fbuilds%2F334647645&node=http%3A%2F%2Fbordercloud.github.io%2FTFT-tests%2FGO3%2FERT-ART%2Fmanifest.ttl%23test_1%2FResponse

**Comment by BorderCloud** [comment]
It's a problem of type by default  for a datetime difference. If you want to change this behaviour by default, you need to rewrite this test... with the W3C ;)

You can push this issue in their project:
https://github.com/w3c/rdf-tests
