### ISSUE TITLE
Some ASK queries are being incorrectly interpreted as failing.

### ISSUE THREAD

**Issue by masda70** [BorderCloud/TFT#6]
The result matches the expected value, but the parsing differs in structure, which causes the test to fail.

http://sparqlscore.com/ajax_testResultNode.php?graph=https%3A%2F%2Ftravis-ci.org%2FBorderCloud%2Ftft-jena-fuseki%2Fbuilds%2F321458219&node=http%3A%2F%2Fwww.w3.org%2F2009%2Fsparql%2Fdocs%2Ftests%2Fdata-sparql11%2Faggregates%2Fmanifest%23agg-groupconcat-01%2FResponse

http://sparqlscore.com/ajax_testResultNode.php?graph=https%3A%2F%2Ftravis-ci.org%2FBorderCloud%2Ftft-stardog%2Fbuilds%2F334647645&node=http%3A%2F%2Fwww.w3.org%2F2009%2Fsparql%2Fdocs%2Ftests%2Fdata-sparql11%2Ffunctions%2Fmanifest%23now01%2FResponse

http://sparqlscore.com/ajax_testResultNode.php?graph=https%3A%2F%2Ftravis-ci.org%2FBorderCloud%2Ftft-jena-fuseki%2Fbuilds%2F321458219&node=http%3A%2F%2Fwww.w3.org%2F2009%2Fsparql%2Fdocs%2Ftests%2Fdata-sparql11%2Ffunctions%2Fmanifest%23now01%2FResponse

**Comment by BorderCloud** [comment]
It's corrected. Thanks.
